### ISSUE TITLE
Any JSON-RPC Interface to Broadcast Signed Transaction

### ISSUE THREAD

**Issue by Wangmmx** [Cocos-BCX/cocos-mainnet#115]
Is there a transaction broadcast  rpc interface? When I used `broadcast_transaction`, reported an error 
`method not found`, and returned an rpc list which do not have any broadcast api

`"api":[["about",3],["add_extern_sign_key",33],["add_file_relate_account",49],["add_operation_to_builder_transaction",5],["adjustment_temporary_authorization",30],["approve_proposal",133],["asset_update_restricted_list",65],["begin_builder_transaction",4],["bid_collateral",93],["borrow_asset",77],["buy",76],["call_contract_function",20],["cancel_crontab",55],["cancel_nh_asset_order",45],["cancel_order",78],["create_account_with_brain_key",73],["create_asset",82],["create_committee_member",94],["create_contract",21],["create_crontab",54],["create_file",48],["create_nh_asset",37],["create_nh_asset_order",43],["create_witness",100],["create_world_view",35],["crontab_builder_transaction",57],["dbg_generate_blocks",135],["dbg_push_blocks",134],["dbg_stream_json_objects",136],["dbg_update_object",137],["delete_nh_asset",42],["derive_owner_keys_from_brain_key",70],["dump_private_keys",16],["file_signature",50],["fill_nh_asset_order",46],["get_account",106],["get_account_contract_data",23],["get_account_count",110],["get_account_history",111],["get_account_id",107],["get_account_top_transaction",28],["get_account_transaction",29],["get_asset",88],["get_bitasset_data",89],["get_block",108],["get_block_by_id",109],["get_call_orders",124],["get_chain_properties",31],["get_collateral_bids",113],["get_committee_member",97],["get_contract",24],["get_contract_public_data",25],["get_dynamic_global_properties",117],["get_global_properties",116],["get_key_label",143],["get_limit_orders",123],["get_market_history",115],["get_nh_creator",41],["get_object",118],["get_order_book",145],["get_private_key",119],["get_prototype_operation_by_idx",130],["get_prototype_operation_by_name",129],["get_public_key",144],["get_relative_account_history",112],["get_settle_orders",125],["get_signature_keys",62],["get_transaction_by_id",26],["get_transaction_id",81],["get_transaction_in_block_info",27],["get_vesting_balances",102],["get_witness",96],["gethelp",1],["global_settle_asset",91],["help",0],["import_balance",67],["import_key",66],["info",2],["is_locked",12],["is_new",11],["is_public_key_registered",114],["issue_asset",87],["list_account_balances",19],["list_account_created_file",52],["list_account_crontab",56],["list_account_nh_asset",39],["list_account_nh_asset_order",47],["list_accounts",18],["list_asset_restricted_objects",64],["list_assets",63],["list_committee_members",99],["list_my_accounts",17],["list_nh_asset_by_creator",38],["list_nh_asset_order",44],["list_witnesses",98],["load_wallet_file",120],["lock",13],["lookup_file",53],["network_add_nodes",138],["network_get_connected_peers",139],["normalize_brain_key",122],["preview_builder_transaction",7],["propose_builder_transaction",9],["propose_fee_change",132],["propose_parameter_change",131],["propose_relate_parent_file",51],["propose_relate_world_view",36],["publish_asset_feed",86],["quit",121],["read_memo",141],["recover_crontab",58],["register_account",71],["register_nh_asset_creator",34],["remove_builder_transaction",10],["replace_operation_in_builder_transaction",6],["reserve_asset",90],["revise_contract",22],["save_wallet_file",126],["sell",75],["sell_asset",74],["serialize_transaction",127],["set_key_label",142],["set_node_deduce_in_verification_mode",60],["set_node_message_send_cache_size",59],["set_password",15],["settle_asset",92],["sign_builder_transaction",8],["sign_memo",140],["sign_transaction",128],["suggest_brain_address_key",69],["suggest_brain_key",68],["transfer",79],["transfer2",80],["transfer_nh_asset",40],["unlock",14],["update_asset",83],["update_asset_feed_producers",85],["update_bitasset",84],["update_collateral_for_gas",61],["update_committee_member",95],["update_witness",101],["upgrade_account",72],["validate_transaction",32],["vote_for_committee_member",104],["vote_for_witness",105],["withdraw_vesting",103]]}`

**Comment by luis360** [comment]
yes, the response I received is Assert Exception: _local_apis.size()> api_id using broadcast_transaction to send transfer

**Comment by luis360** [comment]
Did you solve it？

**Comment by Wangmmx** [comment]
> Did you solve it？

Yes, a new broadcast interface was provided, and closed
